"""Add user to getTweet table

Revision ID: b449cbe5f61e
Revises: 
Create Date: 2023-03-20 01:40:47.933225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b449cbe5f61e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    with op.batch_alter_table('get_tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('get_tweet', schema=None) as batch_op:
        batch_op.drop_column('user')

    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('link', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
